export default {
    REQUESTED_LOGIN: 'REQUESTED_LOGIN',
    FAILED_LOGIN: 'FAILED_LOGIN',
    LOGIN: 'LOGIN',
    LOGOUT: 'LOGOUT',
    NO_SESSION: 'NO_SESSION',
    
    REQUESTED_SIGNUP: 'REQUESTED_SIGNUP',
    FAILED_SIGNUP: 'FAILED_SIGNUP',
    SIGNUP: 'SIGNUP',

    RECIEVED_STAGES: 'RECIEVED_STAGES',
    FAILED_STAGES: 'FAILED_STAGES',

    RECIEVED_PROJECTS: 'RECIEVED_PROJECTS',
    UPDATED_SELECTED_PROJECT: 'UPDATED_SELECTED_PROJECT',
    ADDED_PROJECT: 'ADDED_PROJECT',
    FAILED_PROJECT_ADITION: 'FAILED_PROJECT_ADITION',

    RECIEVED_TEAMS: 'RECIEVED_TEAMS',
    FAILED_TEAM_ADITION: 'FAILED_TEAM_ADITION',
    ADDED_TEAM: 'ADDED_TEAM',

    RECIEVED_TASK_COMMENTS: 'RECIEVED_TASK_COMMENTS',
    FAILED_COMMENT_ADITION: 'FAILED_COMMENT_ADITION',
    ADDED_COMMENT: 'ADDED_COMMENT',

    RECIEVED_TASKS: 'RECIEVED_TASKS',
    ADDED_TASK: 'ADDED_TASK',
    FAILED_TASK_ADITION: 'FAILED_TASK_ADITION',
    UPDATED_TASK: 'UPDATED_TASK',
    FAILED_TASK_UPDATE: 'FAILED_TASK_UPDATE',

    REQUESTED_EVENTS: 'REQUESTED_EVENTS',
    RECIEVED_EVENTS: 'RECIEVED_EVENTS',

    SENT_CHART_OPTIONS: 'SENT_CHART_OPTIONS',
    REQUESTED_CHART_OPTIONS: 'REQUESTED_CHART_OPTIONS',
    RECIEVED_CHART_OPTIONS: 'RECIEVED_CHART_OPTIONS',
};
