export default {
    REQUESTED_LOGIN: 'REQUESTED_LOGIN',
    FAILED_LOGIN: 'FAILED_LOGIN',
    LOGIN: 'LOGIN',
    
    REQUESTED_SIGNUP: 'REQUESTED_SIGNUP',
    FAILED_SIGNUP: 'FAILED_SIGNUP',
    SIGNUP: 'SIGNUP',

    RECIEVED_STAGES: 'RECIEVED_STAGES',
    FAILED_STAGES: 'FAILED_STAGES',

    RECIEVED_TASKS: 'RECIEVED_TASKS',
    ADDED_TASK: 'ADDED_TASK',
    FAILED_TASK_ADITION: 'FAILED_TASK_ADITION',
};
