export default {
    REQUESTED_LOGIN: 'REQUESTED_LOGIN',
    FAILED_LOGIN: 'FAILED_LOGIN',
    LOGIN: 'LOGIN',
    RECIEVED_TASKS: 'RECIEVED_TASKS',
    ADDED_TASK: 'ADDED_TASK',
    FAILED_TASK_ADITION: 'FAILED_TASK_ADITION',
};
